// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nxnbrdamgnzoadacbtaf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im54bmJyZGFtZ256b2FkYWNidGFmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4MDcyOTQsImV4cCI6MjA2OTM4MzI5NH0.36zJrsJ08n1F6gKQwHBDBOFI4WqCsLN5Z9vZoVfLw8M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});